image:
  path: "static/img/logo.png"
spring:
  velocity:
    resource-loader-path: classpath:/templates/velocity
  datasource:
    url: "${POSTGRES_URL}"
    username: "${POSTGRES_USERNAME}"
    password: "${POSTGRES_PASSWORD}"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: "${GOOGLE_MAIL_USERNAME}"
    password: "${GOOGLE_MAIL_PASSWORD}"
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    enable:
      all: true
  prometheus:
    metrics:
      export:
        enabled: true