global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'finance-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['finance-service:8082']
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8081']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8080']